export const SET_MAIL_LIST = "SET_MAIL_LIST";

export const SET_MAIL_TO_LIST = "SET_MAIL_TO_LIST";

export const SET_MAIL_TEMP_LIST = "SET_MAIL_TEMP_LIST";

export const SET_READ_MAIL = "SET_READ_MAIL";

export const SET_MAIL_LIST_DEFAULT = "SET_MAIL_LIST_DEFAULT";

export const SET_ADDRESS_LIST = "SET_ADDRESS_LIST";

export const CHECK_ADDRESS_LIST = "CHECK_ADDRESS_LIST";

export const RESET_ADDRESS_LIST = "RESET_ADDRESS_LIST";
